apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  ports:
    - name: brokerext
      port: 9092
      targetPort: 9092
    - name: brokerint
      port: 29092
      targetPort: 29092
  selector:
    service: kafka-instance
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: kafka-instance
  name: kafka-instance
spec:
  selector:
    matchLabels:
      service: kafka-instance
  serviceName: "kafka"
  replicas: 1
  template:
    metadata:
      labels:
        service: kafka-instance
    spec:
      enableServiceLinks: false
      hostname: kafka
      containers:
      - env:
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENERS
          value: "LISTENER_INT://:29092,LISTENER_EXT://:9092,"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "LISTENER_INT://kafka:29092,LISTENER_EXT://localhost:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "LISTENER_EXT:PLAINTEXT,LISTENER_INT:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "LISTENER_INT"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo1:2181"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        image: bitnami/kafka:latest
        name: kafka-instance
        ports:
          - containerPort: 9092
          - containerPort: 29092