apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: kafka-ui
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: kafka-ui
  name: kafka-ui
spec:
  selector:
    matchLabels:
      service: kafka-ui
  serviceName: "kafka-ui"
  replicas: 1
  template:
    metadata:
      labels:
        service: kafka-ui
    spec:
      containers:
        - env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:29092
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: zoo1:2181
          image: provectuslabs/kafka-ui:master
          name: kafka-ui
          ports:
            - containerPort: 8080
